version: '2'
services:
  
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
  cucumber:
    build:
      context: .
      dockerfile: Dockerfile  
    volumes: 
      - /user/temp:/app/prints
    depends_on:
      - hub
    links:
      - hub
