version: '2'

services:
  react-web:
    image: react-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    entrypoint: "tail -f /dev/null"

  react-web-tests:
    image: react-web-tests
    depends_on:
        - react-web
    build:
        context: .
        dockerfile: Dockerfile.cucumber
    volumes:
        - "./:/cucumberApp"
entrypoint: "tail -f /dev/null"

cucumber-firefox:
  build: .
  command: bundle exec cucumber -f pretty -f json -o cucumber.json
  volumes:
- .:/myap
