version: '2'
services:
  firefox:
    image: selenium/node-firefox
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
  chrome:
    image: selenium/node-chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
  cucumber:
    build:
      context: .
      dockerfile: Dockerfile  
    volumes: 
      - /user/temp:/app/result
    depends_on:
      - hub
    links:
      - hub
